apiVersion: v1
kind: Secret
metadata:
  name: climapp-secret
  labels:
    app: climapp
type: Opaque
stringData:
  # Database credentials
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "PostgresqlChilling2310.*"
  DATABASE_URL: "postgresql+psycopg2://postgres:PostgresqlChilling2310.*@climapp-db-service:5432/climapp"
  
  # API Keys
  WEATHER_API_KEY: "b1c7d0d62d817d95e3b09960a0a70ca4"
  API_KEY: "b1c7d0d62d817d95e3b09960a0a70ca4"
